apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:                               #customization of the Service
  type: ClusterIP                   #type of Cluster IP
  selector:
    component: web
  ports:
    - port: 3000           #port to incoming traffic
      targetPort: 3000       #port for acessing the Pod with the selector label